[package]
name = "fuel-core-executor"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "fuel", "fuel-vm"]
license = { workspace = true }
repository = { workspace = true }
description = "Fuel Block Executor"

[dependencies]
anyhow = { workspace = true }
fuel-core-chain-config = { workspace = true }
fuel-core-storage = { workspace = true }
fuel-core-types = { workspace = true }
fuel-core-database = { workspace = true }
parking_lot = { workspace = true }
tracing = { workspace = true }
hex = { version = "0.4", features = ["serde"] }


[dev-dependencies]
fuel-core-trace = { path = "../../trace" }
