[package]
name = "fuel-benches-outputs"
version = "0.0.0"
edition = { workspace = true }
license = { workspace = true }
publish = false

[dependencies]
fuel-core-types = { path = "../../crates/types", version = "0.16.1", default-features = false, features = ["random", "test-helpers"] }

[workspace]
