[package]
name = "fuel-core-graphql"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
homepage = { workspace = true }
keywords = ["blockchain", "fuel", "fuel-vm"]
license = { workspace = true }
repository = { workspace = true }
description = "Fuel GraphQL"

[dependencies]
anyhow = { workspace = true }
async-graphql = { version = "4.0", features = [
    "tracing",
], default-features = false }
async-trait = { workspace = true }
axum = { workspace = true }
clap = { workspace = true, features = ["derive"] }
derive_more = { version = "0.99" }
enum-iterator = "1.2"
fuel-core-chain-config = { workspace = true }
fuel-core-metrics = { workspace = true }
fuel-core-services = { workspace = true }
fuel-core-storage = { workspace = true }
fuel-core-txpool = { workspace = true }
fuel-core-types = { workspace = true, features = [
    "serde",
] }
futures = { workspace = true }
hex = { version = "0.4", features = ["serde"] }
hyper = { version = "0.14" }
itertools = { workspace = true }
num_cpus = "1.13"
postcard = { workspace = true, features = ["use-std"] }
primitive-types = "0.12"
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["raw_value"] }
strum = "0.24"
strum_macros = "0.24"
tempfile = { workspace = true, optional = true }
thiserror = "1.0"
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
tokio-stream = { workspace = true, features = ["sync"] }
tower-http = { version = "0.3", features = ["set-header", "trace"] }
tracing = { workspace = true }
uuid = { version = "1.1", features = ["v4"] }

[dev-dependencies]
assert_matches = "1.5"
fuel-core-services = { path = "./../../services", features = ["test-helpers"] }
fuel-core-storage = { path = "./../../storage", features = ["test-helpers"] }
fuel-core-trace = { path = "./../../trace" }
fuel-core-types = { path = "./../../types", features = ["test-helpers"] }
mockall = { workspace = true }
test-case = { workspace = true }

[features]
test-helpers = []
metrics = []
debug = ["fuel-core-types/debug"]
default = ["debug"]
