[package]
edition = { workspace = true }
license = { workspace = true }
name = "fuel-core-benches"
publish = false
version = "0.0.0"

[dependencies]
clap = { workspace = true, features = ["derive"] }
criterion = { version = "0.4", features = ["html_reports"] }
ctrlc = "3.2.3"
fuel-core = { workspace = true, default-features = false, features = [
    "rocksdb",
] }
fuel-core-storage = { workspace = true }
fuel-core-types = { workspace = true, features = ["test-helpers"] }
rand = { workspace = true }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
serde_yaml = "0.9.13"

[[bench]]
harness = false
name = "vm"
